/*
 * ini.h
 */

#ifndef INI_H_
#define INI_H_

#define APP_VERSION				"1.3"

#define EXIT_ON_WRONG_FW_DEPENDENCY
#define MIN_DEPEND_FW_VER_MAJOR		5
#define MIN_DEPEND_FW_VER_MINOR		0
#define MIN_DEPEND_FW_VER_BUILD		43

#define EXIT_ON_WRONG_LIB_DEPENDENCY
#define MIN_DEPEND_LIB_VER_MAJOR	5
#define MIN_DEPEND_LIB_VER_MINOR	0
#define MIN_DEPEND_LIB_VER_BUILD	43

#endif /* INI_H_ */
